# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Programming and digital collaboration for entrepreneurs, start ups and small business owners.
name: keyboard_colab
email: keyboardcolab@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    I am a programmer and entrepreneur with a love for start ups and open source software. 
    I've been involved with various business ventures and various software projects. 
    This is simply an account of the things I've learned along the way. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://keyboardcolab.co.uk" # the base hostname & protocol for your site
twitter_username: 
github_username:  

# Build settings
markdown: kramdown
